// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYcjjk_eOUxlMKk-it7ukEG4oTVtJ_bcY',
    appId: '1:267021312026:web:10055ae4f9e47dd9daf1a3',
    messagingSenderId: '267021312026',
    projectId: 'agora-test-c54f5',
    authDomain: 'agora-test-c54f5.firebaseapp.com',
    storageBucket: 'agora-test-c54f5.appspot.com',
    measurementId: 'G-RZM9Q9NRD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs1tPjcuFLp1oxJkfnsWlrxwx7PnlMmbg',
    appId: '1:267021312026:android:5423f8eb29115465daf1a3',
    messagingSenderId: '267021312026',
    projectId: 'agora-test-c54f5',
    storageBucket: 'agora-test-c54f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD-yO1d2J2z_IjzfiLJy69Cc2LgMI0Mvw',
    appId: '1:267021312026:ios:fbda3c4a353c0dffdaf1a3',
    messagingSenderId: '267021312026',
    projectId: 'agora-test-c54f5',
    storageBucket: 'agora-test-c54f5.appspot.com',
    iosClientId: '267021312026-bdm7gj0ll15c1as01646tqp5qlsq178b.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraTest',
  );
}
